
name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code 
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run tests
              run: |
                pytest tests/

            - name: Build Docker image
              run: |
                docker build -t Examensarbete .

            - name: Log in to Docker hub
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                DB_USER: ${{ secrets.DB_USER }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
              run: |
                echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

            - name: Push Docker image
              run:
                docker tag Examensarbete $DOCKER_USERNAME/Examensarbete:latest
                docker push $DOCKER_USERNAME/Examensarbete:latest
                